<!-- GENERATED -->

<template>
<div>
    <div><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">artist</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_text">&nbsp;-&nbsp;</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">title</span><span class="__renamer_syntax_operator">%</span></div>
    <div><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">tracknumber</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_text">.&nbsp;</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">artist</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_text">&nbsp;-&nbsp;</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">title</span><span class="__renamer_syntax_operator">%</span></div>
    <div><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">artist</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_text">&nbsp;-&nbsp;</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">title</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_text">&nbsp;-&nbsp;</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">bpm</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_text">&nbsp;-&nbsp;</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">key</span><span class="__renamer_syntax_operator">%</span></div>
    <div><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">artist</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_text">&nbsp;-&nbsp;</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">album</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_text">/</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">tracknumber</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_text">&nbsp;-&nbsp;</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">title</span><span class="__renamer_syntax_operator">%</span></div>
    <div><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">year</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_text">&nbsp;-&nbsp;</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">album</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_text">/</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">track</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_text">&nbsp;-&nbsp;</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">artist</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_text">&nbsp;-&nbsp;</span><span class="__renamer_syntax_operator">%</span><span class="__renamer_syntax_variable">title</span><span class="__renamer_syntax_operator">%</span></div>
</div>
</template>

<script>
export default {
    name: 'HelpRenamerExamples'
}
</script>